version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#    LOGIN_PASSWORD: "dockerLoginPassword"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      #- docker login –u User –p $LOGIN_PASSWORD
  build:
    commands:
      - echo Entered the build phase...
      - npm run build
  post_build:
    commands:
#      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - aws s3 sync dist s3://piab-sabio-live-demo --delete --acl public-read
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
#cache:
#  paths:
#    - '/root/.m2/**/*'
